### ISSUE TITLE
Running the playnite 720 bat from client wont open playnite nor close it once opened. 

### ISSUE THREAD

**Issue by gagrecco** [cgarst/gamestream_launchpad#10]
So I am trying to run it via moonlight from my switch. When I open it the screen does go to 720p but thats it. Playnites does not open, on my client I can see my screen but I have to manually open it. and closing the stream wont close playnite. 
also one enhancement could be a "Switch version" where it opens playnite and swaps the control  a for b and x for y. I dont know how hard is it, but a good touch.

**Comment by cgarst** [comment]
Could you try connecting the same way from Moonlight on your phone and see if it’s the same?

-Corey
________________________________

**Comment by gagrecco** [comment]
Nothing. Tried it 4 times from my phone. Resolution changed, playnite did not opened. I openend playnite manually, close the stream. Resolution went back to normal, but playnite remained opened

**Comment by gagrecco** [comment]
maybe I need some further steps. My playnite is in a games folder at C drives. do I need to set that up or something?

**Comment by cgarst** [comment]
Where is your Playnite installed? Can you post your INI file?

-Corey
________________________________

**Comment by cgarst** [comment]
Yes, it must be specified in the Playnite ini file.

-Corey
________________________________

**Comment by gagrecco** [comment]
let me see if I can lol. Kind of a noob with this stuff. On the playnite ini or the desktop ini? I will procerde to change it on the playnite ini

**Comment by gagrecco** [comment]
supp I manage for playnite to open. But it still does not close. and furthermore if it doesent close, I cant reopen the stream

**Comment by gagrecco** [comment]
btw I am trying to open the Playnite.FullscreenApp. It opens fine, now the closing is the problem. I have try the name on the task manager and on the taskbar with no success

**Comment by gagrecco** [comment]
also its kind of bugged as it, does not opens in full full screen cause I can still see the  taskbar. and when I opened a game in my monitor was fullscreen but in my phone and my switch it was just a smalll window on the side. 
Please tell me what info can I provide to help you with a troubleshoot

**Comment by cgarst** [comment]
The taskbar issue has been fixed. Looks like the original issue was resolved with a path update. This tool won't close Playnite when the GameStream session ends, the intended workflow is the opposite: to close Playnite yourself which will end the GameStream.
