### ISSUE TITLE
Choose a monitor?

### ISSUE THREAD

**Issue by jamie9090** [cgarst/gamestream_launchpad#3]
This may just be a GFE limitation.

However, I use a headless dummy HDMI adapter (1 of 3 monitor identities).

Finding Gamestream only streams to the "1" monitor identity, regardless of what has been marked as "main display".

It even forces it back on when you disconnect it.

Thanks for the awesome tool!

**Comment by cgarst** [comment]
This sounds like a GFE limitation however I'm unsure that I understand. What's the purpose the dummy adapter when you have 2 other displays? Are you unable to swap the ports around so that the dummy is in slot 1?

**Comment by jamie9090** [comment]
Ah, I'm probably overcomplicating it. I'll give that a go - thank you.

**Comment by cgarst** [comment]
So also, if you can find a way to solve the problem within a session via command prompt, you could put that command in a `.bat` script and use that script as one of your [background program](https://github.com/cgarst/gamestream_launchpad#customization) within this tool and it'll run every session. Maybe something with `DisplaySwitch.exe` would help per [this](https://www.reddit.com/r/ShieldAndroidTV/comments/gfc4i2/dual_monitor_pc_via_moonlight_problem/g318ofl/)?

**Comment by jamie9090** [comment]
Great thinking! Will certainly keep it in mind.

Looking forward to diving into your tool. Thanks for putting it together.
