### ISSUE TITLE
Gog Galaxy 2 launcher support

### ISSUE THREAD

**Issue by kdpkke** [cgarst/gamestream_launchpad#6]
Hello there. I contacted you on reddit, but I think opening a issue here is better to let everyone know what I asked you.

Is it possible to have GOG Galaxy 2 launcher support other than playnite (with an option to choose which one the user prefers to use)?

This way you support the most used (maybe the only ones?) launcher on the market! 
Thank you in advance

**Comment by cgarst** [comment]
Thanks for opening an issue. This will be supported in the next release.

**Comment by cgarst** [comment]
Added in 2ee32ee8a1425fd9ec643b8f0408492d29b34922 and release v0.6.
