### ISSUE TITLE
No .exe file in gamestream release v0.6

### ISSUE THREAD

**Issue by Pixxel123** [cgarst/gamestream_launchpad#7]
It appears that your v0.6 release has no `gamestream_launchpad.exe` file.

**Comment by juwens** [comment]
just downloaded the release v0.6 

https://github.com/cgarst/gamestream_launchpad/releases/download/0.6/gamestream_launchpad.zip

![image](https://user-images.githubusercontent.com/11560817/94307054-54aaf280-ff74-11ea-8814-22a478eaf6cd.png)

I guess your antivirus tool moved the file to quarantine/deleted it.

**Comment by cgarst** [comment]
v0.6 was re-uploaded yesterday to include the file, thanks.
