### ISSUE TITLE
Windows taskbar is stuck in front of Playnite

### ISSUE THREAD

**Issue by ByronSpencer** [cgarst/gamestream_launchpad#9]
**Issue:**

When one of the playnite batch files is run (whether locally or via moonlight) the windows taskbar is visible in front of Playnite in Windows 10.

I've narrowed it down to happening in the `while` loop here:
https://github.com/cgarst/gamestream_launchpad/blob/debf358c0fc73bc9d6b237e1919bf7ab0712f06b/gamestream_launchpad.py#L146

The Playnite app handles being fullscreen on its own, and it seems the attempt to maximize it and/or focus it causes it to get stuck behind the Windows taskbar. I'm guessing something in this process causes the fullscreen Playnite's window "forwardness" to invert or overflow to a negative, so it ends up behind everything instead of in front of everything...something like that?

This is likely not an issue for "windowed" apps, but it is for the fullscreen Playnite app. 

**Recommendation:**

I recommend either adding a check if "Playnite" is the launcher window name (or the playnite exe is the target application) and skipping the maximize and/or focus steps, or using a different method to give it focus.

**Steps to reproduce:**

Create an empty text file called `Anything Playnite.txt` and run the batch file and see that:

- If `Anything Playnite.txt` is open, notepad will get maximized and fullscreen Playnite works as expected
- If `Anything Playnite.txt` is closed, fullscreen Playnite gets stuck behind the Windows taskbar

Really any window with "Playnite" in the name will have the same effect.

OS info:
Windows 10 Pro
Version 1909
Build 18363.1082

**How I found this:**

I noticed that if I had the batch file open in notepad for editing, this did not occur when running the batch file is run, but notepad _would_ get maximized. Going through the code I see why this happens (at least in part): 

`cfg_launcher_window_name` is set to "Playnite", which you're looking for so you know what window to focus and maximize. That string also happens to be in the window name for notepad when editing the batch file. So in that circumstance the notepad gets maximized and focused, and the real Playnite is ignored. Closing notepad and running the batch file again results in the taskbar being stuck on top of Playnite again.

**Comment by Zriel88** [comment]
Was going to open an issue for this as I'm having the same issue. Thanks for the thorough explain and hope this gets "fixed" soon.

**Comment by cgarst** [comment]
Thanks for the detailed report. This was a regression from the recent GOG Galaxy support, it's been fixed now in f98ffb9d646edcf1bdd68145702ffb0f9bba12a2 and the latest release.
